federated-isp/LTM.MvcClient/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LTM.MvcClient.Controllers
{
    [Authorize]
    [Route("api/[controller]")]
    public class DataController : Controller
    {
        // GET: api/values
        [HttpGet]
        public string Get()
        {
            return "Secure information from data controller!";
        }
    }
}

federated-isp/LTM.MvcClient/Controllers/HomeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace LTM.MvcClient.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("OpenIdConnect");
        }
    }
}

federated-isp/LTM.MvcClient/Controllers/RestrictedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LTM.MvcClient.Controllers
{
    [Route("restricted")]
    [Authorize]
    public class RestrictedController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

federated-isp/LTM.MvcClient/Views/Home/Index.cshtml
<h1>Página pública</h1>

<div>
    @Html.ActionLink("Página restrita", "Index", "Restricted")
</div>

federated-isp/LTM.MvcClient/Views/Restricted/Index.cshtml
<h1>Página restrita</h1>
<dl>
    @foreach (var claim in User.Claims)
    {
        <dt>@claim.Type</dt>
        <dd>@claim.Value</dd>

    }
</dl>

federated-isp/LTM.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    @if(User != null && User.Identity.IsAuthenticated)
    {
        <div>@Html.ActionLink("Logout", "Logout", "Home")</div>
    }
    <div>
        @RenderBody()
    </div>
</body>
</html>